### ISSUE TITLE
Can I ask what this repo is for?

### ISSUE THREAD

**Issue by sanbox-irl** [Unity-Technologies/com.unity.vscode_editor#1]
Just general curiosity (especially as a VSC user!)

**Comment by miniwolf** [comment]
Investigation into moving editor integration to packages. Making this open source example is one of the ways to teach others how to add support for new editors that does not have native support in unity. In addition allowing public contributions as it will be under an open license. 
It is very much still in the experimental and prone to big changes and being scrapped. But hopefully it will be introduced to unity in the future.

**Comment by hmans** [comment]
> In addition allowing public contributions as it will be under an open license.

I like how no additional commits were ever pushed, and pull requests on this repository are universally ignored. 🥳

**Comment by miniwolf** [comment]
> > In addition allowing public contributions as it will be under an open license.
> 
> I like how no additional commits were ever pushed, and pull requests on this repository are universally ignored. 🥳

This package is being shipped together with Unity as the `com.unity.ide.vscode` package. The source code moved to an internal repo. I am in the process of moving the source code out again. But that requires talks with the legal department.
For now, I cannot take changes from the community, as legal is not in agreement with what license this code should be filed under. The original MIT license may or may not remain.

**Comment by hmans** [comment]
I understand, and I know how these things can be complicated. I apologize for the snark, consider it a way to vent a bit of the frustration over the situation. If it helps, I'd be _extremely_ happy to see current versions of these packages being developed in the open.

**Comment by miniwolf** [comment]
> I'd be _extremely_ happy to see current versions of these packages being developed in the open.

The same goes for me. The plan from the code editor side is to make all three code editor packages open-source here on Github. But that all depends on how these conversations resolve.
